### PR TITLE
React API: Quotes

### PR DESCRIPTION
**Pull request by fdezcaminero**
Features
* New component displaying quotes
* Fetching data inside the new component
* Loading state
* Error state
* The new component is called inside the main component

### CODE REVIEW

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello @fdezcaminero   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request with a complaint about the reviewer taking too long to review it.

I am going to ask you to be patient the reviewer who is reviewing it will submit the review when he is done making the review. 

**Also kindly note the following:**

KIndly only request for a second opinion only when you are having an issue with a review that was made by a reviewer and not raise a "False" alarm.

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Review by sumairq — APPROVED** [review]
### Hi @fdezcaminero , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Quotes are being fetched
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fdezcaminero** [comment]
Sorry @Nemwel-Boniface
I didn't mean to raise a false alarm. It's unusual for code reviewers to take so long. I thought there might have been some kind of problem receiving the request. Or something similar.

I don't know what the protocol is in these cases. How long is too long? If nothing's the matter, then I'll wait, of course.

**Comment by Nemwel-Boniface** [comment]
Hello @fdezcaminero  I believe that it being a weekend, it might be a little slower than during the weekday. However, you should never worry since there will always be someone available to make your review or assist with anything.

Have a great rest of your weekend and #happycoding :rocket:  as always.

**Pull request merged**
